#ifndef RINGY_LOGO_H
#define RINGY_LOGO_H

#include <stdint.h>
#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Raw pixel/map data generated by the LVGL image converter */
extern const uint8_t ringy_logo_map[];

/* LVGL image descriptor (defined in ringy_logo.c) */
extern const lv_image_dsc_t ringy_logo;

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* RINGY_LOGO_H */
