
#ifndef WIFI_MANAGER_PUBLIC_H
#define WIFI_MANAGER_PUBLIC_H

#ifdef __cplusplus
extern "C" {
#endif

#define WIFI_MANAGER_MAX_SSID_LENGTH            32
#define WIFI_MANAGER_MAX_PASS_LENGTH            63

typedef enum _WIFI_MANAGER_CONFIGURATION_STATE_E
{
    WIFI_MANAGER_CONFIGURATION_STATE_NOT_CONFIGURED             = 0,
    WIFI_MANAGER_CONFIGURATION_STATE_WAITING_CONFIGURATION      = 1,
    WIFI_MANAGER_CONFIGURATION_STATE_CONFIGURED                 = 2,
} WIFI_MANAGER_CONFIGURATION_STATE_E;

#ifdef __cplusplus
}
#endif

#endif /* WIFI_MANAGER_PUBLIC_H */